<?php

/**
 * @file
 * The Social Open Graph module.
 */

use Drupal\Core\File\FileExists;
use Drupal\embed\Entity\EmbedButton;
use Drupal\file\Entity\File;

/**
 * Implements hook_theme().
 */
function social_open_graph_theme($existing, $type, $theme, $path) {
  return [
    'open_graph' => [
      'variables' => [
        'url' => NULL,
        'image' => NULL,
        'providerName' => NULL,
        'title' => NULL,
        'description' => NULL,
      ],
    ],
  ];
}

/**
 * Function that creates an embed button with a custom icon.
 */
function _social_open_graph_create_media_button(): void {
  // Get the module handler service.
  $module_handler = \Drupal::service('module_handler');

  // Create a File entity for the icon.
  $path = $module_handler->getModule('social_open_graph')->getPath();
  $image_path = $path . DIRECTORY_SEPARATOR . 'assets' . DIRECTORY_SEPARATOR . 'icons' . DIRECTORY_SEPARATOR . 'kiwi.svg';
  $uri = \Drupal::service('file_system')->copy($image_path, 'public://kiwi.svg', FileExists::Replace);

  $media = File::create([
    'langcode' => 'en',
    'uid' => 1,
    'status' => 1,
    'uri' => $uri,
  ]);
  $media->save();

  // Create an embed icon.
  $button = EmbedButton::create([
    'id' => 'social_open_graph',
    'label' => t('Open Graph URL'),
    'langcode' => 'en',
    'status' => TRUE,
    'icon_uuid' => $media->uuid(),
    'type_id' => 'url',
    'type_settings' => [],
  ]);
  $button->save();
}
